#!/usr/bin/env python3
"""Build the active NikaS Climate module graph into one autonomous bundle."""
from __future__ import annotations

import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "custom_components" / "nikas_climate" / "frontend"
SOURCE_ENTRYPOINT = FRONTEND / "nikas-climate-entry-160.js"
PRODUCTION_BUNDLE = FRONTEND / "nikas-climate-production.js"
IMPORT_RE = re.compile(
    r'^import\s+["\'](?P<path>\./[^"\'?]+\.js)(?:\?[^"\']*)?["\'];\s*$',
    re.MULTILINE,
)


def build() -> tuple[str, list[Path]]:
    """Return a deterministic depth-first bundle and its source order."""
    visited: set[Path] = set()
    visiting: set[Path] = set()
    ordered: list[tuple[Path, str]] = []

    def visit(path: Path) -> None:
        path = path.resolve()
        if path in visited:
            return
        if path in visiting:
            raise RuntimeError(f"Cyclic frontend import: {path.relative_to(ROOT)}")
        if path.parent != FRONTEND.resolve() or not path.is_file():
            raise RuntimeError(f"Frontend import leaves its source directory: {path}")
        visiting.add(path)
        source = path.read_text(encoding="utf-8")
        imports = list(IMPORT_RE.finditer(source))
        for match in imports:
            visit(path.parent / match.group("path"))
        body = IMPORT_RE.sub("", source).strip()
        if re.search(r"^\s*(?:import|export)\b", body, re.MULTILINE):
            raise RuntimeError(f"Unsupported module syntax remains in {path.name}")
        visiting.remove(path)
        visited.add(path)
        ordered.append((path, body))

    visit(SOURCE_ENTRYPOINT)
    source_names = ", ".join(path.name for path, _ in ordered)
    parts = [
        "/* Generated by scripts/build-frontend.py. Do not edit directly.",
        f" * Sources ({len(ordered)}): {source_names}",
        " */",
        '"use strict";',
        "",
    ]
    for path, body in ordered:
        parts.extend(
            (
                f"/* source: {path.name} */",
                "(() => {",
                body,
                "})();",
                "",
            )
        )
    return "\n".join(parts), [path for path, _ in ordered]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed production bundle differs from its sources",
    )
    args = parser.parse_args()
    rendered, sources = build()
    if args.check:
        if not PRODUCTION_BUNDLE.is_file():
            raise SystemExit(f"Missing production bundle: {PRODUCTION_BUNDLE}")
        if PRODUCTION_BUNDLE.read_text(encoding="utf-8") != rendered:
            raise SystemExit(
                "Production bundle is stale; run python scripts/build-frontend.py"
            )
        print(f"OK deterministic production bundle from {len(sources)} modules")
        return
    PRODUCTION_BUNDLE.write_text(rendered, encoding="utf-8")
    print(f"Built {PRODUCTION_BUNDLE.relative_to(ROOT)} from {len(sources)} modules")


if __name__ == "__main__":
    main()
